### ISSUE TITLE
where to put pretrained ELMo for other domains

### ISSUE THREAD

**Issue by amandalynne** [allenai/allennlp-website#118]
On the [ELMo page](https://allennlp.org/elmo), there is a place for pre-trained models and a place for contributed models; neither of these tables seems like the right place to add domain-specific ELMo, e.g. the ELMo trained on PubMed by @matt-peters available [on S3](https://s3.console.aws.amazon.com/s3/buckets/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway_PubMed_large/?region=us-west-2&tab=overview).

The pre-trained model table reports each model's F1 scores for SRL and Constituency Parsing, so it wouldn't make sense to put  the domain-specific ELMo in that table as we wouldn't report performance of the domain-specific model on generic text (I assume). On the other hand, the PubMed ELMo was not 'contributed' by a third party. 

Should there be a new section for domain-specific pre-trained ELMo models on the page? Or, should the existing sections be broadened in scope?

**Comment by matt-gardner** [comment]
Does it make sense to put [here](https://github.com/allenai/allennlp/blob/master/MODELS.md)?

**Comment by matt-peters** [comment]
Good question -- how about we just add it to the "Contributed ELMo Models" section, but change the wording of the description to "ELMo models have been trained for other languages and domains. We maintain a list of models here but are unable to respond to quality issues ourselves."

**Comment by nstfk** [comment]
HI..
I am trying to find details on the PubMed ELMO model but I can't.. and I cant access the model itself, is it available publicly ? 

Thanks

**Comment by amandalynne** [comment]
@nstfk check allennlp.org now! they are there under Contributed.

**Comment by MickHardins** [comment]
Hi @matt-peters, i would like to experiment with your Pubmed ELMO model, but after loading the model when i try to get the embeddings i face an error. I think it's related to the vocabulary. Would you mind give me some insights on how to use the model? :) 
Sorry if i asked in the wrong place.

**Comment by schmmd** [comment]
Closing as @amandalynne's problem was resolved.
