### ISSUE TITLE
Tutorial doesn't utilize tqdm

### ISSUE THREAD

**Issue by NicoleJaneway** [allenai/allennlp-website#150]
On https://allennlp.org/tutorials, the intro states "We'll use tqdm to track the progress of our training" but tqdm is not utilized in the example code.

**Comment by matt-gardner** [comment]
The tqdm call is inside of `trainer.train()`.

**Comment by matt-gardner** [comment]
We're redo-ing a bunch of this, and we'll likely be removing this tutorial soon, anyway, so I'm closing the issue instead of clarifying things on the site.
