### ISSUE TITLE
The dataset in the tutorial is missing (400 Bad Request)

### ISSUE THREAD

**Issue by alisianoi** [allenai/allennlp-website#155]
Hi everyone,

I've been following the tutorial here: https://allennlp.org/tutorials

At the step where the train and test dataset are being loaded, I locally get an exception:

```
OSError: HEAD request failed for url https://raw.githubusercontent.com/allenai/allennlp with status code 400
```

https://github.com/allenai/allennlp-website/blob/922994c679d2592b9dd23a42e722a85976960ec9/_includes/default-tutorial.html#L245

My sneaking suspicion is that the link is outdated. Do you have any idea where it went to?

**Comment by alisianoi** [comment]
Additionally, this might be related?

https://github.com/allenai/allennlp/pull/4334

**Comment by matt-gardner** [comment]
That tutorial is out of date and will be removed soon.  Please see the quick start section of the [allennlp guide](https://guide.allennlp.org) instead.
