### ISSUE TITLE
Make section padding consistent on the home page

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-website#52]
![image](https://user-images.githubusercontent.com/8367927/44686102-08420100-aa02-11e8-9997-0838772d6c9e.png)

**Comment by aaronsarnat** [comment]
@schmmd do you only want me to address the spacing issue, or would you also like me to tweak the logo list? As is, these logos are pretty big and kind of inconsistent in their layout. Usually logo lists are more uniform, follow some sort of a grid, and are composed of smaller individual logos:

![image](https://user-images.githubusercontent.com/8367927/44686242-6a9b0180-aa02-11e8-8642-a9a182093616.png)

Time estimate for just the spacing: 15 minutes. Spacing + revisiting logo list layout: 1-2 hrs maybe?

**Comment by schmmd** [comment]
@aaronsarnat for this ticket, let's address the spacing.  Can you cut another for better formatting the logo list?

**Comment by aaronsarnat** [comment]
Sure thing

**Comment by aaronsarnat** [comment]
Fixed in https://github.com/allenai/allennlp-website/pull/55

**Comment by aaronsarnat** [comment]
Closed, as this was merged into master.
