### ISSUE TITLE
Create a "model gallery" of user codebases that implement models in AllenNLP.

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-website#53]
Each model record would include:

- Paper name
- Link to GitHub Repo
- Link to paper
- Contributors (maybe)

---

Will not be prominently featured when first launched, but will likely become more prominent in the future.

**Comment by schmmd** [comment]
@MLatzke recommends https://files.slack.com/files-pri/T0A198UU9-FCHF19770/download/s2-logo-2.svg if we use an icon to link out to Semantic Scholar.

**Comment by aaronsarnat** [comment]
@schmmd I don't have access to that asset. URL redirects me to slack messages.

**Comment by MLatzke** [comment]
@schmmd I sent @aaronsarnat the svg via slack.
