### ISSUE TITLE
Include authors in contributed model list

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-website#72]
We need to add authors to the contributed model list.

![image](https://user-images.githubusercontent.com/954798/45430701-cac4b100-b65a-11e8-8700-07c83f60eaad.png)

We should include the following information:

Deep enhanced representation for implicit discourse relation recognition
Hongxiao Bai, Hai Zhao

Ontology alignment in the biomedical domain using entity definitions and context
Lucy Lu Wang, Chandra Bhagavatula, Mark Neumann, Kyle Lo, Chris Wilhelm, Waleed Ammar

SciTail: A textual entailment dataset from science question answering
Tushar Khot and Ashish Sabharwal and Peter Clark

Bilateral Multi-Perspective Matching for Natural Language Sentences
Zhiguo Wang, Wael Hamza, Radu Florian
Contributed by: [HandsomeZebra](https://github.com/handsomezebra)

**Comment by matt-gardner** [comment]
Related, I think demo.allennlp.org should have a standard format for displaying this information.  Something like

```
Original paper: [title and venue]
Original authors: [list, with affiliation]
This version implemented by: [list, with affiliation]
Description:
```

It'll make it more obvious who should get credit for what when someone is looking at the demo.
