### ISSUE TITLE
Clean how how programatic / bash predictions examples are presented

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-website#82]
Presently they are each presented in the same box with comments separating the two.  Is there a better design?  Would some syntax highlighting make them more presentable?

**Comment by aaronsarnat** [comment]
+1 for syntax highlighting. There's a pretty straightforward way to do that in jekyll.

I also think we should break the code blocks into two separate readonly fields stacked on top of each other. Then we ditch the comments and use field labels instead.

Predictions tab
---

Command line:
```
some bash commands
```

---

As a library:
```
some python code
```
