### ISSUE TITLE
Add Event2Mind model section to website

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-website#86]
Once we make the new `Event2Mind` demo live on prod, we should add the associated model description / prediction / training / evaluation content to https://allennlp.org/models.

---

That content can be edited here: https://github.com/allenai/allennlp-website/blob/master/_data/models.yml

<br>

**Comment by aaronsarnat** [comment]
@brendan-ai2 @maartensap @schmmd FYI

**Comment by aaronsarnat** [comment]
@maartensap to make it easier, you can copy/paste one of the other models in that data file and use this as the description content:

```
The Event2Mind dataset proposes a commonsense inference task between events and mental states. In particular, it takes events as lightly preprocessed text and produces likely intents and reactions for participants of the event. This page demonstrates a reimplementation of [the original Event2Mind system (Rashkin et al, 2018)](https://www.semanticscholar.org/paper/b89f8a9b2192a8f2018eead6b135ed30a1f2144d). An event with people entities should be typed as "PersonX" or "PersonY". Optionally, "___" can be used as a placeholder for objects or phrases.
```

Then you can assign a PR to me for review and i'll make sure the data/HTML side of things looks correct. Will defer to others on the team for the accuracy of the content itself.

**Comment by brendan-ai2** [comment]
Maarten suggests: a draft description (mostly copy pasted from demo page) : "The Event2Mind dataset proposes a commonsense inference task between events and mental states. In particular, it takes events as lightly preprocessed text and produces likely intents and reactions for participants of the event. This model is a reimplementation of the original Event2Mind neural inference model (Rashkin et al, 2018). An event with people entities should be typed as "PersonX" or "PersonY". Optionally, "___" can be used as a placeholder for objects or phrases."

**Comment by aaronsarnat** [comment]
Whatever makes the most sense, just note that inline links are encoded in the data via markdown

**Comment by brendan-ai2** [comment]
(Note to self: Also update https://github.com/allenai/allennlp/blob/master/MODELS.md)
